In [1]:
import numpy as np
input_red = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 156, 155, 156, 158, 158, 0],
    [0, 153, 154, 157, 159, 159, 0],
    [0, 149, 151, 155, 158, 159, 0],
    [0, 146, 146, 149, 153, 158, 0],
    [0, 145, 143, 143, 148, 158, 0],
    [0, 0, 0, 0, 0, 0, 0]
])
input_green = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 167, 166, 167, 169, 169, 0],
    [0, 164, 165, 168, 170, 170, 0],
    [0, 160, 162, 166, 169, 170, 0],
    [0, 156, 156, 159, 163, 168, 0],
    [0, 155, 153, 153, 158, 168, 0],
    [0, 0, 0, 0, 0, 0, 0]
])
input_blue = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 163, 162, 163, 165, 165, 0],
    [0, 160, 161, 164, 166, 166, 0],
    [0, 156, 158, 162, 165, 166, 0],
    [0, 155, 155, 158, 162, 167, 0],
    [0, 154, 152, 152, 157, 167, 0],
    [0, 0, 0, 0, 0, 0, 0]
])
kernel_red = np.array([
    [-1, -1, 1],
    [0, 1, -1],
    [0, 1, 1]
])
kernel_green = np.array([
    [1, 0, 0],
    [1, -1, -1],
    [1, 0, -1]
])
kernel_blue = np.array([
    [0, 1, 1],
    [0, 1, 0],
    [1, -1, 1]
])
bias = 1
def apply_convolution(input_channel, kernel):
    kernel_size = kernel.shape[0]
    input_size = input_channel.shape[0]
    if input_size < kernel_size:
        raise ValueError("Input size must be larger than kernel size.")
    output_size = input_size - kernel_size + 1
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            region = input_channel[i:i+kernel_size, j:j+kernel_size]
            if region.shape == kernel.shape:
                output[i, j] = np.sum(region * kernel)
    return output
output_red = apply_convolution(input_red, kernel_red)
output_green = apply_convolution(input_green, kernel_green)
output_blue = apply_convolution(input_blue, kernel_blue)
final_output = output_red + output_green + output_blue + bias
print("Final Output:")
print(final_output)

Final Output:
[[-25. 466. 466. 475. 653.]
 [295. 787. 798. 812. 671.]
 [291. 776. 784. 800. 659.]
 [293. 771. 773. 782. 645.]
 [159. 328. 324. 319. 335.]]
